stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the application..."
    - docker build -t my-app:latest .

test:
  stage: test
  script:
    - echo "Running tests..."
    - docker run my-app:latest

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - kubectl apply -f k8s/deployment.yaml
  only:
    - main
